let mock = [{
    id: "1",
    name: "Genu Bender",
    abb: "GB",
    type: "TKE",
    duration: "5-10 min",
    tips: "Make sure the patient doesn't lean.",
  },
  {
    id: "2",
    name: "Nustep",
    abb: "None",
    type: "TKE",
    duration: "10-15 min",
    tips: "Make sure the resistance level is appropriate.",
  },
  {
    id: "3",
    name: "Total Gym",
    abb: "TG",
    type: "TKE",
    duration: "5-10 min",
    tips: "Make sure the patient's knees don't go past the feet when they squat.",
  },
  {
    id: "4",
    name: "Short Arc Quads",
    abb: "SAQ",
    type: "TKE",
    duration: "10-20 reps",
    tips: "Make sure the patient holds the knee in an extended position for a couple seconds.",
  },
  {
    id: "5",
    name: "Long Arc Quads",
    abb: "LAQ",
    type: "TKE",
    duration: "10-20 reps",
    tips: "Add a weight if the exercise is too easy",
  },
  {
    id: "6",
    name: "Heel Slides",
    abb: "HS",
    type: "TKE",
    duration: "3 min",
    tips: "Make sure to set a timer!",
  },
  {
    id: "7",
    name: "Quad Sets",
    abb: "QS",
    type: "TKE",
    duration: "10-20 reps",
    tips: "Make sure that they are pushing down AND squeezing those muscles.",
  },
  {
    id: "8",
    name: "Straight Leg Raises",
    abb: "SLR",
    type: "TKE",
    duration: "10-20 reps",
    tips: "If the patient is having a hard time lifting their leg, give them a strap to use.",
  },
  {
    id: "9",
    name: "Total Knee Extensions",
    abb: "TKE",
    type: "TKE",
    duration: "10-20 reps",
    tips: "Make sure that the patient isn't compensating by using their hip to perform the movement.",
  },
  {
    id: "10",
    name: "Hamstring Curls",
    abb: "Ham curls",
    type: "TKE",
    duration: "10-20 reps",
    tips: "Make sure the patient's foot doesn't rest on the ground in between repetitions.",
  },
]

export default mock;
